# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "inventory-aging-markdown-app"
client_id = "810353aad6e2d62f0efaa3451acb3f14"
application_url = "https://zshops-oral-publishing-techno.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_all_orders,read_inventory,read_reports,read_customers,read_fulfillments"

[auth]
redirect_urls = [
  "https://zshops-oral-publishing-techno.trycloudflare.com/auth/callback",
  "https://zshops-oral-publishing-techno.trycloudflare.com/auth/shopify/callback",
  "https://zshops-oral-publishing-techno.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fxhiii.myshopify.com"
